management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
      service: ${spring.application.name}
      source: ${spring.application.name}-${random.uuid}
  tracing:
    # Set to true to forward tracing spans to a local Zipkin instance.
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://benoit.moussaud:9411/api/v2/spans
  otlp:
    metrics:
      export:
        # Set to true to forward metrics to a local OpenTelemetry collector.
        enabled: true
        step: 30s
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
