spring:
  application:
    name: lowercasePetKind
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2
      mode: always
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://otel-collector:4317

logging:
  pattern:
    # Include tracing ids in log entries.
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.renamethis: DEBUG
    org.moussaud: DEBUG
    io.micrometer.core: DEBUG
    org.springframework.web: DEBUG

