#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    resourceclaims.services.apps.tanzu.vmware.com/controller: "true"
  name: mysql-for-kubernetes-mysqls-service-bindings-role
rules:
  - apiGroups: ["sql.tanzu.vmware.com"]
    resources: ["postgres"]
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - mysqls/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-app-operator-reader
  labels:
    apps.tanzu.vmware.com/aggregate-to-app-operator-cluster-access: "true"
rules:
  - apiGroups: ["sql.tanzu.vmware.com"]
    resources: ["mysqls"]
    verbs: ["get", "list", "watch"]
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: tanzu-postgres
spec:
  description:
    short: Tanzun Postgres instances with a postgresql engine
  pool:
    group: sql.tanzu.vmware.com
    kind: MySQL
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: mysql-cross-namespace
  namespace: shared-services
spec:
  consumingNamespaces:
    - "*"
  subject:
    group: sql.tanzu.vmware.com/v1
    kind: Postgres
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: #@ data.values.petKind.lower()+"s-database"
  namespace: dev-tap
spec:
  ref:
    apiVersion: sql.tanzu.vmware.com/v1
    kind: Postgres
    name: #@ data.values.petKind.lower()+"s-database"
    namespace: shared-services
